/* Original-plan events: reuse audited geometry; only rewards and metadata differ. */
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const {solve,replay,prepare,advance,DT,STEP}=require('./lib/chunk-solver.cjs');
const {makeReachable}=require('./lib/chunk-audit.cjs');
const ROOT=path.resolve(__dirname,'..'),context={window:{}};
for(const file of ['chunks-data.js','event-chunks-data.js'])vm.runInNewContext(fs.readFileSync(path.join(ROOT,'src',file),'utf8'),context);
const base=context.window.DSChunksData,rewards=context.window.DSEventChunksData,S=base.strings.slice(),chunks=[],checks=[];
const manifest=JSON.parse(fs.readFileSync(path.join(ROOT,'assets/manifest.json'),'utf8'));
function token(s){let i=S.indexOf(s);if(i<0){i=S.length;S.push(s);}return i;}
function clone(raw,event,index=0){
 const c=JSON.parse(JSON.stringify(raw));c.sourceChunk=c.id;c.id='origin-'+event+'@'+c.speed+'#'+index;c.base=token('origin-'+event);c.event=event;c.motif=event;
 delete c.ribbon;c.requires=[];c.intro=-1;c.trial=0;return c;
}
function geometry(c){return {obstacles:c.o.map(([k,x,opts])=>({kind:S[k],x,opts,...manifest.obstacle[S[k]]})),platforms:c.p.map(([x,y,w,opts])=>({x,y,w,opts})),gaps:c.g.map(([x,w])=>({x,w}))};}
function idleProof(c){
 const shape=geometry(c),env=prepare(shape,c.speed);env.end=c.len+220;env.steps=Math.ceil((env.end-env.start)/c.speed/DT/STEP);
 let state={x:env.start,y:600,vy:0,ground:600,on:true,jumps:0,rise:1,fall:1.55,grav:1,slide:0,sliding:false,down:false,bufferDown:0,coyote:.12,dash:0,grace:0,cooldown:0,usedDash:false,usedBounce:false,visited:{},broken:{},collapse:{},trace:null};
 c.proof=[];c.proofX=[];
 for(let i=0;i<env.steps;i++){c.proof.push(0);c.proofX.push(state.x);state=advance(env,state,0,i);assert.ok(state&&state.on);}
 assert.ok(state.x>=c.len);c.engineChecked=true;
}
function save(c){
 const geo=geometry(c);
 if(c.o.length||c.p.length)assert.ok(replay(geo,c.speed,0,c.proof),'Source witness must still complete '+c.id);
 assert.equal(c.g.length,0,'No forced pits in these events');
 if(c.p.length)assert.ok(makeReachable(geo.platforms,geo.gaps)(c.speed));
 assert.ok(c.r.every(r=>r[0]>=0&&r[0]<c.len&&r[1]>0&&r[1]<600));
 chunks.push(c);checks.push({id:c.id,event:c.event,speed:c.speed,source:c.sourceChunk,obstacles:c.o.length,platforms:c.p.length,pickups:c.r.length,groundSafe:true,optionalRoute:c.optionalProof?true:false});
}
for(const speed of [380,520,700,900]){
 let c=clone(rewards.chunks.find(c=>c.speed===speed&&c.rewardCount===12),'quota-spill');
 c.family=token('reward');c.name='额度漏饭补漏';c.r=c.r.map(([x,y])=>[x,y,token('rice')]);idleProof(c);save(c);
 const cargo=base.chunks.find(c=>c.speed===speed&&c.o.length===1&&base.strings[c.o[0][0]]==='cargo'&&!c.p.length&&!c.g.length);assert.ok(cargo);
 c=clone(cargo,'brain-reboot');c.name='敲箱重启';c.optional=['stomp','dash'];c.min=1;save(c);
 const upper=base.chunks.find(c=>c.speed===speed&&base.strings[c.family]==='reward'&&c.p.length===2&&!c.o.length&&!c.g.length);assert.ok(upper);
 c=clone(upper,'economy-route');c.name='高级票与经济站台';c.optional=['jump','platform'];c.min=1;
 c.r=Array.from({length:6},(_,i)=>[Math.round(65+(c.len-155)*i/5),i%2?540:505,token('rice')]);
 c.r.push([Math.round(c.p[0][0]+c.p[0][2]*.25),c.p[0][1]-64,token('bigrice')],[Math.round(c.p[0][0]+c.p[0][2]*.7),c.p[0][1]-64,token('bigrice')],[Math.round(c.p[1][0]+c.p[1][2]*.5),c.p[1][1]-64,token('bigrice')]);
 const optional=solve({...geometry(c),requiredPlatforms:c.p.map(p=>p[0])},speed);assert.ok(optional,'Optional platforms must be reachable');c.optionalProof=Array.from(optional);save(c);
 for(let real=0;real<3;real++){
  c={id:'origin-proxy-parcels@'+speed+'#'+real,base:token('origin-proxy-parcels'),family:token('reward'),name:'识别真假包裹',min:1,event:'proxy-parcels',speed,len:Math.round(speed*2.6+240),role:'release',topology:'ground',motif:'parcel-choice',actions:[],optional:['jump'],recovery:'long',devices:[],intro:-1,requires:[],trial:0,o:[],p:[],g:[],k:[],h:[],r:[]};
  for(let i=0;i<3;i++)c.r.push([Math.round(150+i*speed*.9),[530,410,285][i],token(i===real?'parcel-real':'parcel-empty')]);
  idleProof(c);save(c);
 }
 c={id:'origin-chip-reclaim@'+speed+'#0',base:token('origin-chip-reclaim'),family:token('reward'),name:'找回高速芯片',min:1,event:'chip-reclaim',speed,len:Math.round(speed*2+220),role:'release',topology:'ground',motif:'chip-pieces',actions:[],optional:['jump'],recovery:'long',devices:[],intro:-1,requires:[],trial:0,o:[],p:[],g:[],k:[],h:[],r:[]};
 for(let i=0;i<3;i++)c.r.push([Math.round(150+i*speed*.7),[510,410,510][i],token('chip-fragment')]);
 idleProof(c);save(c);
}
fs.writeFileSync(path.join(ROOT,'src/origin-event-chunks-data.js'),'/* Generated by tools/build_origin_event_chunks.cjs. */\nwindow.DSOriginEventChunksData='+JSON.stringify({version:1,tolerance:110,strings:S,chunks})+';\n');
fs.writeFileSync(path.join(ROOT,'docs/origin-event-routes-verification.json'),JSON.stringify({chunks:chunks.length,checks},null,2));
console.log('Checked '+chunks.length+' frozen original-plan event routes.');
