/* Offline, hazard-free event rewards. Replayed by the same frozen chunk API. */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {prepare,advance,DT,STEP}=require('./lib/chunk-solver.cjs');
const ROOT=path.resolve(__dirname,'..'),chunks=[],checks=[];
for(const speed of [380,520,700,900])for(const count of [4,6,8,12,14,16,24,26]){
 const waves=count===24?3:count>=12?2:1;
 const duration=count===24?5.8:Math.max(1.4,count*.19),length=Math.round(speed*duration);
 const r=[];
 for(let i=0;i<count;i++){
  const wave=Math.floor(i*waves/count),local=i-Math.ceil(wave*count/waves);
  const x=Math.round(100+(length-180)*(i+.35*wave)/(count-1+.35*(waves-1)));
  const y=count===24&&local===7?240:count===24&&local===3?410:[502,544,494,530][i%4];
  r.push([x,y,2]);
 }
 const c={obstacles:[],platforms:[],gaps:[]},env=prepare(c,speed);
 env.end=length+220;env.steps=Math.ceil((env.end-env.start)/speed/DT/STEP);
 let state={x:env.start,y:600,vy:0,ground:600,on:true,jumps:0,rise:1,fall:1.55,grav:1,slide:0,sliding:false,down:false,bufferDown:0,coyote:.12,dash:0,grace:0,cooldown:0,usedDash:false,usedBounce:false,visited:{},broken:{},collapse:{},trace:null};
 const proof=[],proofX=[];
 for(let i=0;i<env.steps;i++){proofX.push(Math.round(state.x*10)/10);proof.push(0);state=advance(env,state,0,i);assert.ok(state&&state.on&&state.y===600);}
 assert.equal(r.length,count);assert.ok(state.x>=length);assert.ok(r.every(p=>p[0]>=0&&p[0]<length&&p[1]>=240&&p[1]<=544));
 const chunk={id:'event-rice-'+count+'@'+speed+'#0',base:0,family:1,min:0,name:'分波白饭补给',role:'release',topology:'ground',motif:'rice-waves',actions:[],optional:count===24?['jump','double']:[],riskRoute:false,recovery:'long',event:'rice',rewardCount:count,waves,speed,len:length,devices:[],intro:-1,requires:[],trial:0,o:[],p:[],g:[],k:[],h:[],r,proof,proofX,engineChecked:true};
 chunks.push(chunk);checks.push({id:chunk.id,count,waves,seconds:length/speed,groundedExit:true,hazards:0});
}
fs.writeFileSync(path.join(ROOT,'src/event-chunks-data.js'),'/* Generated by tools/build_event_chunks.cjs. */\nwindow.DSEventChunksData='+JSON.stringify({version:1,tolerance:110,strings:['event-rice','reward','rice'],chunks})+';\n');
fs.writeFileSync(path.join(ROOT,'docs/event-reward-routes-verification.json'),JSON.stringify({chunks:chunks.length,checks},null,2));
console.log('Frozen and checked '+chunks.length+' event reward routes.');
